import os
import cv2
import numpy as np


def extract_spatial_metrics(binary_mask_array):
    """Processes Steps 14 and 15: Traces polygon contours to extract isolated landslide

    objects, computing their physical center locations and metric surface areas.
    """
    # 1. Structural Input Sanity Check
    if binary_mask_array is None:
        raise ValueError("Matrix error: Input mask array cannot be empty.")

    # 2. Step 14: Topological Contour Clustering Loop
    # cv2.RETR_EXTERNAL isolates the outermost boundary edges of the landslide polygons
    # cv2.CHAIN_APPROX_SIMPLE compresses horizontal, vertical, and diagonal segments to optimize RAM
    contours, _ = cv2.findContours(
        binary_mask_array, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
    )

    print(f"Geospatial Topology Engine: Identified {len(contours)} raw structural anomalies.")

    structured_landslide_objects = []

    # 3. Step 15: Geometric Calculus on Individual Anomaly Patches
    for idx, contour in enumerate(contours):
        # Calculate spatial moments (physics-based pixel distribution metrics)
        moments = cv2.moments(contour)

        # Extract the area footprint count (total number of positive pixels in the polygon)
        pixel_area = moments["m00"]

        # Filter out minor single-pixel optimization noise (anomalies smaller than 3 pixels)
        if pixel_area < 3:
            continue

        # Calculate spatial coordinate centers (Centroids) using moment equations:
        # X_center = m10 / m00  |  Y_center = m01 / m00
        # Add a tiny epsilon factor (1e-8) to the denominator to prevent division-by-zero math crashes
        centroid_x = int(moments["m10"] / (moments["m00"] + 1e-8))
        centroid_y = int(moments["m01"] / (moments["m00"] + 1e-8))

        # Translate grid pixels into true surface metrics using the Sentinel-2 configuration:
        # 1 pixel = 10 meters spatial resolution -> 10m * 10m = 100 square meters footprint area
        metric_surface_area_sqm = pixel_area * 100

        # Construct localized key-value metadata dictionaries for each isolated object
        landslide_metadata = {
            "object_id": idx + 1,
            "centroid_pixel": (centroid_x, centroid_y),
            "total_pixels": int(pixel_area),
            "surface_area_sqm": metric_surface_area_sqm,
            "contour_points": contour,
        }

        structured_landslide_objects.append(landslide_metadata)

    return structured_landslide_objects


# --- Script Local Operational Verification Loop ---
if __name__ == "__main__":
    print("Starting Step 14 and 15 Spatial Processing Verification Check...")

    # Look for any predicted numpy file generated by predict.py in your directory
    all_files = os.listdir(".")
    predicted_arrays = sorted([f for f in all_files if f.startswith("predicted_mask_") and f.endswith(".npy")])

    if len(predicted_arrays) == 0:
        print("Information Notice: No active prediction mask array found on disk.")
        print("Simulating a dummy structural hazard matrix to test computational pathways...")
        
        # Build an artificial mock matrix simulation: 128x128 pixels, initialized to zero background
        sample_mask = np.zeros((128, 128), dtype=np.uint8)
        # Injection block: Draw a solid filled white square at grid location (40,40) to (60,60)
        # Size = 20 * 20 = 400 pixels total area
        sample_mask[40:60, 40:60] = 1
        source_label = "Simulated_Mock_Patch"
    else:
        # Load the actual computed file matrix array off your laptop drive
        sample_file_name = predicted_arrays[0]
        sample_mask = np.load(sample_file_name)
        source_label = sample_file_name

    print(f"Processing target data matrix baseline: {source_label}")

    # Run the spatial math engine pipelines
    extracted_hazards = extract_spatial_metrics(sample_mask)

    # --- Technical Summary Output for University Report Document ---
    print(f"\n================== SPATIAL MATH ENGINE METRICS ==================")
    print(f"Pipeline executed successfully.")
    print(f"Total Valid Valid Landslide Objects Retained: {len(extracted_hazards)}")
    print("------------------------------------------------------------------")
    
    for hazard in extracted_hazards:
        print(f"Anomaly ID: {hazard['object_id']}")
        print(f"  Centroid Location (X, Y Grid Matrix) : {hazard['centroid_pixel']}")
        print(f"  Internal Pixel Footprint Component   : {hazard['total_pixels']} cells")
        print(f"  Computed Surface Footprint Metrics   : {hazard['surface_area_sqm']:,} square meters")
        print(f"  Equivalent Footprint Hectares Size   : {hazard['surface_area_sqm'] / 10000:.2f} ha")
        print("------------------------------------------------------------------")
    print("==================================================================\n")
